uri = QgsDataSourceUri()
uri.setParam('pageSize','10000')
uri.setParam('pagingEnabled', 'true')
uri.setParam('preferCoordinatesForWfsT11', 'false')
uri.setParam('restrictToRequestBBOX', '1')
uri.setParam('service', 'wfs')
uri.setParam('version', '2.0.0')
uri.setParam('request', 'GetFeature')
uri.setParam('typename', 'wfs_du:zone_urba')
uri.setParam('srsName', 'EPSG:2354')
#uri.setUsername('me')
#uri.setPassword('my_password')
uri.setParam('url', 'https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs')
layer = QgsVectorLayer(uri.uri(), 'test', 'WFS')

QgsProject.instance().addMapLayer(layer)
print ('termine')